In [114]:
import pandas as pd
import numpy as np
import statistics as stat
study=pd.read_csv('oj.csv')

In [4]:
#1.	Find the dimensions of the oj data set

study.shape

(28947, 17)

In [13]:
#2.	Find the structure of the data set
study.dtypes

store         int64
brand        object
week          int64
logmove     float64
feat          int64
price       float64
AGE60       float64
EDUC        float64
ETHNIC      float64
INCOME      float64
HHLARGE     float64
WORKWOM     float64
HVAL150     float64
SSTRDIST    float64
SSTRVOL     float64
CPDIST5     float64
CPWVOL5     float64
dtype: object

In [9]:
#Find out the column names in the data set
list(study.columns.values)

['store',
 'brand',
 'week',
 'logmove',
 'feat',
 'price',
 'AGE60',
 'EDUC',
 'ETHNIC',
 'INCOME',
 'HHLARGE',
 'WORKWOM',
 'HVAL150',
 'SSTRDIST',
 'SSTRVOL',
 'CPDIST5',
 'CPWVOL5']

In [16]:
#4.	Describe the data set
study.describe()

,store,week,logmove,feat,price,AGE60,EDUC,ETHNIC,INCOME,HHLARGE,WORKWOM,HVAL150,SSTRDIST,SSTRVOL,CPDIST5,CPWVOL5
count,28947.000000,28947.000000,28947.000000,28947.000000,28947.000000,28947.000000,28947.000000,28947.000000,28947.000000,28947.000000,28947.000000,28947.000000,28947.000000,28947.000000,28947.000000,28947.000000
mean,80.883511,100.459944,9.167864,0.237261,2.282488,0.173130,0.225220,0.155557,10.616735,0.115602,0.359178,0.343766,5.097274,1.207317,2.120359,0.438914
std,35.576511,34.692314,1.019378,0.425411,0.648001,0.061872,0.109945,0.187581,0.282314,0.030168,0.052673,0.239028,3.472386,0.526528,0.729828,0.219248
min,2.000000,40.000000,4.158883,0.000000,0.520000,0.058054,0.049550,0.024247,9.867083,0.013506,0.244463,0.002509,0.132097,0.400000,0.772530,0.094562
25%,53.000000,70.000000,8.489616,0.000000,1.790000,0.122100,0.145985,0.041910,10.456079,0.097938,0.312636,0.123486,2.767046,0.727273,1.626192,0.271673
50%,86.000000,101.000000,9.034080,0.000000,2.170000,0.170655,0.229390,0.074656,10.635326,0.111221,0.355635,0.346154,4.650687,1.115385,1.963412,0.383227
75%,111.000000,130.000000,9.764685,0.000000,2.730000,0.213949,0.284395,0.187761,10.796960,0.135168,0.402313,0.528313,6.650602,1.538462,2.533672,0.560240
max,137.000000,160.000000,13.482016,1.000000,3.870000,0.307398,0.528362,0.995691,11.236197,0.216354,0.472308,0.916699,17.855951,2.571429,4.107902,1.143367

In [22]:
#1.	Fetch the first row 3rd column from the data set
print(study.iloc[0,2])

40

In [25]:
#2.	Fetch the first, second and Third columns of the oj data frame
print(study.iloc[:,0:3])

       store      brand  week
0          2  tropicana    40
1          2  tropicana    46
2          2  tropicana    47
3          2  tropicana    48
4          2  tropicana    50
5          2  tropicana    51
6          2  tropicana    52
7          2  tropicana    53
8          2  tropicana    54
9          2  tropicana    57
10         2  tropicana    58
11         2  tropicana    59
12         2  tropicana    60
13         2  tropicana    61
14         2  tropicana    62
15         2  tropicana    63
16         2  tropicana    64
17         2  tropicana    65
18         2  tropicana    66
19         2  tropicana    67
20         2  tropicana    68
21         2  tropicana    69
22         2  tropicana    70
23         2  tropicana    71
24         2  tropicana    72
25         2  tropicana    73
26         2  tropicana    74
27         2  tropicana    75
28         2  tropicana    76
29         2  tropicana    77
...      ...        ...   ...
28917    137  dominicks   131
28918    137  dominicks   132
28919    137  dominicks   133
28920    137  dominicks   134
28921    137  dominicks   135
28922    137  dominicks   136
28923    137  dominicks   137
28924    137  dominicks   138
28925    137  dominicks   139
28926    137  dominicks   140
28927    137  dominicks   141
28928    137  dominicks   142
28929    137  dominicks   143
28930    137  dominicks   144
28931    137  dominicks   145
28932    137  dominicks   146
28933    137  dominicks   147
28934    137  dominicks   148
28935    137  dominicks   149
28936    137  dominicks   150
28937    137  dominicks   151
28938    137  dominicks   152
28939    137  dominicks   153
28940    137  dominicks   154
28941    137  dominicks   155
28942    137  dominicks   156
28943    137  dominicks   157
28944    137  dominicks   158
28945    137  dominicks   159
28946    137  dominicks   160

[28947 rows x 3 columns]

In [27]:
#3.	Fetch the first, second, eighth and the 456th rows of the 1st, third and the sixth columns of the data frame
print(study.iloc[[1,2,8,456],[1,3,6]])

           brand   logmove     AGE60
1      tropicana  8.723231  0.232865
2      tropicana  8.253228  0.232865
8      tropicana  9.049232  0.232865
456  minute.maid  8.392990  0.117368

In [53]:
#4.	Fetch the top 5 rows of the brand column
study["brand"].head()

0    tropicana
1    tropicana
2    tropicana
3    tropicana
4    tropicana
Name: brand, dtype: object

In [52]:
#5.	Fetch top 5 rows of the brand, week and feat details
study.loc[0:6,["brand","week","feat"]]

       brand  week  feat
0  tropicana    40     0
1  tropicana    46     0
2  tropicana    47     0
3  tropicana    48     0
4  tropicana    50     0
5  tropicana    51     0
6  tropicana    52     0

In [131]:
#6.	Fetch the details of all distinct stores
study.store.unique

<bound method Series.unique of 0          2
1          2
2          2
3          2
4          2
5          2
6          2
7          2
8          2
9          2
10         2
11         2
12         2
13         2
14         2
15         2
16         2
17         2
18         2
19         2
20         2
21         2
22         2
23         2
24         2
25         2
26         2
27         2
28         2
29         2
        ...
28917    137
28918    137
28919    137
28920    137
28921    137
28922    137
28923    137
28924    137
28925    137
28926    137
28927    137
28928    137
28929    137
28930    137
28931    137
28932    137
28933    137
28934    137
28935    137
28936    137
28937    137
28938    137
28939    137
28940    137
28941    137
28942    137
28943    137
28944    137
28945    137
28946    137
Name: store, Length: 28947, dtype: int64>

In [79]:
#7.	Fetch all the observations for Tropicana brand
study[study.brand=='tropicana']

,store,brand,week,logmove,feat,price,AGE60,EDUC,ETHNIC,INCOME,HHLARGE,WORKWOM,HVAL150,SSTRDIST,SSTRVOL,CPDIST5,CPWVOL5
0,2,tropicana,40,9.018695,0,3.87,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
1,2,tropicana,46,8.723231,0,3.87,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
2,2,tropicana,47,8.253228,0,3.87,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
3,2,tropicana,48,8.987197,0,3.87,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
4,2,tropicana,50,9.093357,0,3.87,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
5,2,tropicana,51,8.877382,0,3.87,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
6,2,tropicana,52,9.294682,0,3.29,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
7,2,tropicana,53,8.954674,0,3.29,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
8,2,tropicana,54,9.049232,0,3.29,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
9,2,tropicana,57,8.613230,0,3.29,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
10,2,tropicana,58,8.680672,0,3.56,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
11,2,tropicana,59,9.034080,0,3.56,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
12,2,tropicana,60,8.691483,0,3.56,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
13,2,tropicana,61,8.831712,0,3.56,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
14,2,tropicana,62,9.128696,0,3.87,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
15,2,tropicana,63,9.405907,0,2.99,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
16,2,tropicana,64,9.447150,0,2.99,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
17,2,tropicana,65,8.783856,0,3.59,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
18,2,tropicana,66,8.723231,0,3.59,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
19,2,tropicana,67,9.957976,0,2.39,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
20,2,tropicana,68,9.426741,0,2.39,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
21,2,tropicana,69,9.156095,0,3.59,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
22,2,tropicana,70,9.793673,0,2.59,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
23,2,tropicana,71,9.149316,0,2.59,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
24,2,tropicana,72,8.743851,0,3.59,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
25,2,tropicana,73,8.841014,0,3.59,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
26,2,tropicana,74,9.727228,0,2.49,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
27,2,tropicana,75,8.743851,0,3.59,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
28,2,tropicana,76,8.979165,0,3.59,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
29,2,tropicana,77,8.723231,0,3.59,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28721,137,tropicana,131,11.551531,0,1.79,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28722,137,tropicana,132,10.603014,0,1.95,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28723,137,tropicana,133,10.474241,0,2.76,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28724,137,tropicana,134,11.521528,1,2.50,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28725,137,tropicana,135,11.142673,0,2.59,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28726,137,tropicana,136,10.072386,0,3.19,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28727,137,tropicana,137,10.155335,0,2.74,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28728,137,tropicana,138,11.294570,1,2.39,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28729,137,tropicana,139,10.324301,0,3.19,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28730,137,tropicana,140,10.236525,0,3.19,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28731,137,tropicana,141,9.898676,0,3.19,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28732,137,tropicana,142,10.047761,0,3.19,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28733,137,tropicana,143,11.885096,1,2.49,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28734,137,tropicana,144,11.514524,0,2.25,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28735,137,tropicana,145,11.436131,1,1.99,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28736,137,tropicana,146,9.618469,1,3.13,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28737,137,tropicana,147,10.673596,0,2.67,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28738,137,tropicana,148,10.189568,0,3.15,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28739,137,tropicana,149,10.229621,0,3.18,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28740,137,tropicana,150,9.772011,0,3.19,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28741,137,tropicana,151,9.734832,0,3.17,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28742,137,tropicana,152,9.908276,1,3.09,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28743,137,tropicana,153,9.711843,0,3.19,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28744,137,tropicana,154,10.782948,1,2.79,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28745,137,tropicana,155,10.298768,0,2.77,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28746,137,tropicana,156,11.313498,1,2.49,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28747,137,tropicana,157,10.628133,0,2.66,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28748,137,tropicana,158,9.936535,0,3.11,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28749,137,tropicana,159,10.855917,1,2.79,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28750,137,tropicana,160,10.236525,0,2.88,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761

In [118]:
#8.Fetch all the observations for Tropicana brand using query function

study.query("(brand=='tropicana')")

,store,brand,week,logmove,feat,price,AGE60,EDUC,ETHNIC,INCOME,HHLARGE,WORKWOM,HVAL150,SSTRDIST,SSTRVOL,CPDIST5,CPWVOL5
0,2,tropicana,40,9.018695,0,3.87,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
1,2,tropicana,46,8.723231,0,3.87,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
2,2,tropicana,47,8.253228,0,3.87,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
3,2,tropicana,48,8.987197,0,3.87,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
4,2,tropicana,50,9.093357,0,3.87,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
5,2,tropicana,51,8.877382,0,3.87,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
6,2,tropicana,52,9.294682,0,3.29,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
7,2,tropicana,53,8.954674,0,3.29,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
8,2,tropicana,54,9.049232,0,3.29,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
9,2,tropicana,57,8.613230,0,3.29,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
10,2,tropicana,58,8.680672,0,3.56,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
11,2,tropicana,59,9.034080,0,3.56,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
12,2,tropicana,60,8.691483,0,3.56,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
13,2,tropicana,61,8.831712,0,3.56,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
14,2,tropicana,62,9.128696,0,3.87,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
15,2,tropicana,63,9.405907,0,2.99,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
16,2,tropicana,64,9.447150,0,2.99,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
17,2,tropicana,65,8.783856,0,3.59,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
18,2,tropicana,66,8.723231,0,3.59,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
19,2,tropicana,67,9.957976,0,2.39,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
20,2,tropicana,68,9.426741,0,2.39,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
21,2,tropicana,69,9.156095,0,3.59,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
22,2,tropicana,70,9.793673,0,2.59,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
23,2,tropicana,71,9.149316,0,2.59,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
24,2,tropicana,72,8.743851,0,3.59,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
25,2,tropicana,73,8.841014,0,3.59,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
26,2,tropicana,74,9.727228,0,2.49,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
27,2,tropicana,75,8.743851,0,3.59,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
28,2,tropicana,76,8.979165,0,3.59,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
29,2,tropicana,77,8.723231,0,3.59,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28721,137,tropicana,131,11.551531,0,1.79,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28722,137,tropicana,132,10.603014,0,1.95,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28723,137,tropicana,133,10.474241,0,2.76,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28724,137,tropicana,134,11.521528,1,2.50,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28725,137,tropicana,135,11.142673,0,2.59,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28726,137,tropicana,136,10.072386,0,3.19,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28727,137,tropicana,137,10.155335,0,2.74,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28728,137,tropicana,138,11.294570,1,2.39,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28729,137,tropicana,139,10.324301,0,3.19,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28730,137,tropicana,140,10.236525,0,3.19,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28731,137,tropicana,141,9.898676,0,3.19,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28732,137,tropicana,142,10.047761,0,3.19,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28733,137,tropicana,143,11.885096,1,2.49,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28734,137,tropicana,144,11.514524,0,2.25,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28735,137,tropicana,145,11.436131,1,1.99,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28736,137,tropicana,146,9.618469,1,3.13,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28737,137,tropicana,147,10.673596,0,2.67,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28738,137,tropicana,148,10.189568,0,3.15,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28739,137,tropicana,149,10.229621,0,3.18,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28740,137,tropicana,150,9.772011,0,3.19,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28741,137,tropicana,151,9.734832,0,3.17,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28742,137,tropicana,152,9.908276,1,3.09,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28743,137,tropicana,153,9.711843,0,3.19,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28744,137,tropicana,154,10.782948,1,2.79,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28745,137,tropicana,155,10.298768,0,2.77,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28746,137,tropicana,156,11.313498,1,2.49,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28747,137,tropicana,157,10.628133,0,2.66,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28748,137,tropicana,158,9.936535,0,3.11,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28749,137,tropicana,159,10.855917,1,2.79,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28750,137,tropicana,160,10.236525,0,2.88,0.209602,0.528362,0.11325,10.966490,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761

In [117]:
#9.	Fetch bottom 5 observations for those who have bought Tropicana or dominics

study.query("(brand=='tropicana') or (brand=='dominics')").tail(5)

,store,brand,week,logmove,feat,price,AGE60,EDUC,ETHNIC,INCOME,HHLARGE,WORKWOM,HVAL150,SSTRDIST,SSTRVOL,CPDIST5,CPWVOL5
28746,137,tropicana,156,11.313498,1,2.49,0.209602,0.528362,0.11325,10.96649,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28747,137,tropicana,157,10.628133,0,2.66,0.209602,0.528362,0.11325,10.96649,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28748,137,tropicana,158,9.936535,0,3.11,0.209602,0.528362,0.11325,10.96649,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28749,137,tropicana,159,10.855917,1,2.79,0.209602,0.528362,0.11325,10.96649,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761
28750,137,tropicana,160,10.236525,0,2.88,0.209602,0.528362,0.11325,10.96649,0.092996,0.330293,0.860739,6.026484,0.705882,0.77253,0.333761

In [126]:
#10.Fetch the income, brand, price observations with Tropicana brand without feature advertisement

study.query("(brand=='tropicana') and (feat==0)").loc[:,['INCOME','brand','price']]

          INCOME      brand  price
0      10.553205  tropicana   3.87
1      10.553205  tropicana   3.87
2      10.553205  tropicana   3.87
3      10.553205  tropicana   3.87
4      10.553205  tropicana   3.87
5      10.553205  tropicana   3.87
6      10.553205  tropicana   3.29
7      10.553205  tropicana   3.29
8      10.553205  tropicana   3.29
9      10.553205  tropicana   3.29
10     10.553205  tropicana   3.56
11     10.553205  tropicana   3.56
12     10.553205  tropicana   3.56
13     10.553205  tropicana   3.56
14     10.553205  tropicana   3.87
15     10.553205  tropicana   2.99
16     10.553205  tropicana   2.99
17     10.553205  tropicana   3.59
18     10.553205  tropicana   3.59
19     10.553205  tropicana   2.39
20     10.553205  tropicana   2.39
21     10.553205  tropicana   3.59
22     10.553205  tropicana   2.59
23     10.553205  tropicana   2.59
24     10.553205  tropicana   3.59
25     10.553205  tropicana   3.59
26     10.553205  tropicana   2.49
27     10.553205  tropicana   3.59
28     10.553205  tropicana   3.59
29     10.553205  tropicana   3.59
...          ...        ...    ...
28710  10.966490  tropicana   2.39
28711  10.966490  tropicana   2.34
28712  10.966490  tropicana   2.29
28713  10.966490  tropicana   2.37
28714  10.966490  tropicana   3.18
28715  10.966490  tropicana   3.19
28716  10.966490  tropicana   3.19
28718  10.966490  tropicana   3.19
28720  10.966490  tropicana   1.79
28721  10.966490  tropicana   1.79
28722  10.966490  tropicana   1.95
28723  10.966490  tropicana   2.76
28725  10.966490  tropicana   2.59
28726  10.966490  tropicana   3.19
28727  10.966490  tropicana   2.74
28729  10.966490  tropicana   3.19
28730  10.966490  tropicana   3.19
28731  10.966490  tropicana   3.19
28732  10.966490  tropicana   3.19
28734  10.966490  tropicana   2.25
28737  10.966490  tropicana   2.67
28738  10.966490  tropicana   3.15
28739  10.966490  tropicana   3.18
28740  10.966490  tropicana   3.19
28741  10.966490  tropicana   3.17
28743  10.966490  tropicana   3.19
28745  10.966490  tropicana   2.77
28747  10.966490  tropicana   2.66
28748  10.966490  tropicana   3.11
28750  10.966490  tropicana   2.88

[8045 rows x 3 columns]

In [128]:
#11.Add a new column in the dataset: logInc which is the logarithm of the income

study["LogInc"]=np.log(study.INCOME)
study.head()

,store,brand,week,logmove,feat,price,AGE60,EDUC,ETHNIC,INCOME,HHLARGE,WORKWOM,HVAL150,SSTRDIST,SSTRVOL,CPDIST5,CPWVOL5,LogInc
0,2,tropicana,40,9.018695,0,3.87,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927,2.35643
1,2,tropicana,46,8.723231,0,3.87,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927,2.35643
2,2,tropicana,47,8.253228,0,3.87,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927,2.35643
3,2,tropicana,48,8.987197,0,3.87,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927,2.35643
4,2,tropicana,50,9.093357,0,3.87,0.232865,0.248935,0.11428,10.553205,0.103953,0.303585,0.463887,2.110122,1.142857,1.92728,0.376927,2.35643

In [98]:
#12.Sort the Data in the increasing order of the week
print(study.sort_values(by='week').head())

       store        brand  week   logmove  feat  price     AGE60      EDUC  \
0          2    tropicana    40  9.018695     0   3.87  0.232865  0.248935
8141      59  minute.maid    40  7.655391     0   2.62  0.110819  0.233036
8025      59    tropicana    40  8.489616     0   3.19  0.110819  0.233036
26035    124  minute.maid    40  8.269757     0   3.17  0.119626  0.261876
7907      56    dominicks    40  8.565602     1   1.59  0.192889  0.237551

         ETHNIC     INCOME   HHLARGE   WORKWOM   HVAL150  SSTRDIST   SSTRVOL  \
0      0.114280  10.553205  0.103953  0.303585  0.463887  2.110122  1.142857
8141   0.024247  10.715040  0.140676  0.390696  0.292652  0.217275  1.000000
8025   0.024247  10.715040  0.140676  0.390696  0.292652  0.217275  1.000000
26035  0.572356  10.258957  0.124950  0.348519  0.416316  6.328747  0.727273
7907   0.041356  10.831825  0.105928  0.362168  0.578125  4.865721  0.533333

        CPDIST5   CPWVOL5
0      1.927280  0.376927
8141   3.331154  0.395539
8025   3.331154  0.395539
26035  1.793796  0.202169
7907   2.998578  0.496127

In [104]:
#13.Sort the data in the decreasing order of Income
print(study.sort_values(['INCOME'],ascending=[False])).head()

       store        brand  week    logmove  feat  price     AGE60      EDUC  \
8379      62    tropicana    46   9.264829     0   3.87  0.222534  0.517760
8508      62  minute.maid    59   8.540910     0   3.17  0.222534  0.517760
8488      62    tropicana   159  10.263676     1   2.79  0.222534  0.517760
8489      62    tropicana   160   9.609922     0   2.97  0.222534  0.517760
8490      62  minute.maid    40   8.449343     0   3.17  0.222534  0.517760
8491      62  minute.maid    41  10.667652     1   1.99  0.222534  0.517760
8492      62  minute.maid    42   8.754003     0   3.17  0.222534  0.517760
8493      62  minute.maid    43   8.489616     0   3.17  0.222534  0.517760
8494      62  minute.maid    44  10.313741     1   2.59  0.222534  0.517760
8495      62  minute.maid    45   8.528331     0   3.17  0.222534  0.517760
8496      62  minute.maid    46   8.971067     0   3.17  0.222534  0.517760
8497      62  minute.maid    48   8.378391     0   3.17  0.222534  0.517760
8498      62  minute.maid    49  10.518457     1   1.99  0.222534  0.517760
8499      62  minute.maid    50   9.208739     0   3.17  0.222534  0.517760
8500      62  minute.maid    51   8.691483     0   3.17  0.222534  0.517760
8501      62  minute.maid    52   8.601534     0   3.17  0.222534  0.517760
8502      62  minute.maid    53  10.140297     1   2.19  0.222534  0.517760
8503      62  minute.maid    54   8.378391     0   3.17  0.222534  0.517760
8504      62  minute.maid    55   8.691483     0   3.17  0.222534  0.517760
8505      62  minute.maid    56   9.176163     0   3.17  0.222534  0.517760
8506      62  minute.maid    57  10.241102     1   1.99  0.222534  0.517760
8487      62    tropicana   158   9.534161     0   3.19  0.222534  0.517760
8486      62    tropicana   157   9.797238     0   2.49  0.222534  0.517760
8485      62    tropicana   156  10.463332     1   2.49  0.222534  0.517760
8474      62    tropicana   145  11.379988     1   1.99  0.222534  0.517760
8466      62    tropicana   136   9.605620     0   3.19  0.222534  0.517760
8467      62    tropicana   137   9.772011     0   3.19  0.222534  0.517760
8468      62    tropicana   138  10.588603     1   2.39  0.222534  0.517760
8469      62    tropicana   139   9.442087     0   3.19  0.222534  0.517760
8470      62    tropicana   140   9.481893     0   3.19  0.222534  0.517760
...      ...          ...   ...        ...   ...    ...       ...       ...
11742     75    dominicks    56   8.407378     0   1.79  0.207699  0.219548
11743     75    dominicks    57   7.203406     0   2.69  0.207699  0.219548
11744     75    dominicks    58  11.082512     1   1.24  0.207699  0.219548
11745     75    dominicks    59   7.655391     0   1.59  0.207699  0.219548
11746     75    dominicks    60   9.609922     1   1.59  0.207699  0.219548
11747     75    dominicks    61  10.016816     0   1.29  0.207699  0.219548
11748     75    dominicks    62   9.086137     0   0.99  0.207699  0.219548
11749     75    dominicks    63   9.957976     1   1.59  0.207699  0.219548
11731     75    dominicks    45   7.203406     0   2.69  0.207699  0.219548
11730     75    dominicks    44   7.714231     0   2.69  0.207699  0.219548
11729     75    dominicks    43   8.392990     0   2.69  0.207699  0.219548
11728     75    dominicks    42   8.147867     0   2.69  0.207699  0.219548
11711     75  minute.maid   146   8.269757     0   2.60  0.207699  0.219548
11712     75  minute.maid   147   9.618469     1   1.99  0.207699  0.219548
11713     75  minute.maid   148   8.515592     1   2.41  0.207699  0.219548
11714     75  minute.maid   149   8.712760     0   2.89  0.207699  0.219548
11715     75  minute.maid   150  11.299336     1   1.49  0.207699  0.219548
11716     75  minute.maid   151   8.407378     0   2.86  0.207699  0.219548
11717     75  minute.maid   152   9.442087     1   1.92  0.207699  0.219548
11718     75  minute.maid   153  11.233000     1   1.89  0.207699  0.219548
11719     75  minute.maid   154  10.437405     1   1.82  0.207699  0.219548
11720     75  minute.maid   155  10.044987     0   1.69  0.207699  0.219548
11721     75  minute.maid   156   9.895455     0   1.73  0.207699  0.219548
11722     75  minute.maid   157  10.313741     1   1.99  0.207699  0.219548
11723     75  minute.maid   158   8.286017     0   2.81  0.207699  0.219548
11724     75  minute.maid   159   8.540910     0   2.64  0.207699  0.219548
11725     75  minute.maid   160  10.747810     1   2.19  0.207699  0.219548
11726     75    dominicks    40   9.169518     1   1.59  0.207699  0.219548
11727     75    dominicks    41   7.987524     0   2.69  0.207699  0.219548
11577     75    tropicana   130   9.221478     0   1.79  0.207699  0.219548

         ETHNIC     INCOME   HHLARGE   WORKWOM   HVAL150  SSTRDIST   SSTRVOL  \
8379   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8508   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8488   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8489   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8490   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8491   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8492   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8493   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8494   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8495   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8496   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8497   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8498   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8499   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8500   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8501   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8502   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8503   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8504   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8505   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8506   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8487   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8486   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8485   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8474   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8466   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8467   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8468   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8469   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
8470   0.026511  11.236197  0.103979  0.322765  0.916699  5.452685  0.705882
...         ...        ...       ...       ...       ...       ...       ...
11742  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11743  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11744  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11745  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11746  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11747  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11748  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11749  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11731  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11730  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11729  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11728  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11711  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11712  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11713  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11714  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11715  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11716  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11717  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11718  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11719  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11720  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11721  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11722  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11723  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11724  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11725  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11726  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11727  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769
11577  0.415999   9.867083  0.063965  0.315583  0.496000  7.192667  2.230769

        CPDIST5   CPWVOL5
8379   2.184050  0.201722
8508   2.184050  0.201722
8488   2.184050  0.201722
8489   2.184050  0.201722
8490   2.184050  0.201722
8491   2.184050  0.201722
8492   2.184050  0.201722
8493   2.184050  0.201722
8494   2.184050  0.201722
8495   2.184050  0.201722
8496   2.184050  0.201722
8497   2.184050  0.201722
8498   2.184050  0.201722
8499   2.184050  0.201722
8500   2.184050  0.201722
8501   2.184050  0.201722
8502   2.184050  0.201722
8503   2.184050  0.201722
8504   2.184050  0.201722
8505   2.184050  0.201722
8506   2.184050  0.201722
8487   2.184050  0.201722
8486   2.184050  0.201722
8485   2.184050  0.201722
8474   2.184050  0.201722
8466   2.184050  0.201722
8467   2.184050  0.201722
8468   2.184050  0.201722
8469   2.184050  0.201722
8470   2.184050  0.201722
...         ...       ...
11742  1.375126  0.703182
11743  1.375126  0.703182
11744  1.375126  0.703182
11745  1.375126  0.703182
11746  1.375126  0.703182
11747  1.375126  0.703182
11748  1.375126  0.703182
11749  1.375126  0.703182
11731  1.375126  0.703182
11730  1.375126  0.703182
11729  1.375126  0.703182
11728  1.375126  0.703182
11711  1.375126  0.703182
11712  1.375126  0.703182
11713  1.375126  0.703182
11714  1.375126  0.703182
11715  1.375126  0.703182
11716  1.375126  0.703182
11717  1.375126  0.703182
11718  1.375126  0.703182
11719  1.375126  0.703182
11720  1.375126  0.703182
11721  1.375126  0.703182
11722  1.375126  0.703182
11723  1.375126  0.703182
11724  1.375126  0.703182
11725  1.375126  0.703182
11726  1.375126  0.703182
11727  1.375126  0.703182
11577  1.375126  0.703182

[28947 rows x 17 columns]

AttributeError: 'NoneType' object has no attribute 'head'

In [106]:
#14.Find the mean of the juice price for each brand
group=study.groupby('brand')
group['price'].mean()

brand
dominicks      1.735809
minute.maid    2.241162
tropicana      2.870493
Name: price, dtype: float64

In [107]:
#15.Find the average income for each brand and at each store
group=study.groupby(['brand','store'])
group['price'].mean()

brand      store
dominicks  2        1.791273
           5        1.733707
           8        1.664322
           9        1.702308
           12       1.841826
           14       1.825897
           18       1.653750
           21       1.610917
           28       1.755043
           32       1.831667
           33       1.842222
           40       1.576460
           44       1.713879
           45       1.705966
           47       1.752982
           48       1.757119
           49       1.726903
           50       1.705763
           51       1.746786
           52       1.841043
           53       1.829496
           54       1.745702
           56       1.730254
           59       1.588448
           62       1.833675
           64       1.728505
           67       1.666379
           68       1.842435
           70       1.604167
           71       1.831913
                      ...
tropicana  101      2.897355
           102      2.728696
           103      2.733826
           104      2.891130
           105      2.760252
           106      2.895966
           107      2.924917
           109      3.036555
           110      2.920855
           111      3.011250
           112      2.735254
           113      2.916975
           114      2.772821
           115      2.841802
           116      2.901197
           117      2.941356
           118      2.979748
           119      2.812101
           121      2.763051
           122      2.614050
           123      3.009250
           124      3.035372
           126      2.890672
           128      2.998151
           129      2.809138
           130      2.973158
           131      2.893534
           132      2.740000
           134      2.665057
           137      2.883980
Name: price, Length: 249, dtype: float64

In [160]:
#16.Find:
#a.	Mean and std deviation of the income
#b.	For income greater than or equal to 10.5, find the mean income
#c.	For each brand having price >=2.5 find the mean, median, sd of the log of income

print(study.INCOME.mean())
print(stat.pstdev(study.INCOME))

print(study[study.INCOME>=10.5].INCOME.mean())

print(study[study.price>=2.5].groupby(['brand']).INCOME.mean())
print(study[study.price>=2.5].groupby(['brand']).INCOME.median())
print(study[study.price>=2.5].groupby(['brand']).INCOME.std())

10.616734638000503
0.28230874507213854
10.759452382031103
brand
dominicks      10.473626
minute.maid    10.601137
tropicana      10.615601
Name: INCOME, dtype: float64
brand
dominicks      10.367190
minute.maid    10.632364
tropicana      10.635326
Name: INCOME, dtype: float64
brand
dominicks      0.410146
minute.maid    0.300719
tropicana      0.282522
Name: INCOME, dtype: float64

In [132]:
#17.Find the Cross tabulation of brands and feature advertisement
pd.crosstab(study.brand,study.feat)

feat            0     1
brand
dominicks    7169  2480
minute.maid  6865  2784
tropicana    8045  1604